name: 'GH actions stale run canceller'
author: 'Dmitry Rozhdestvenskiy <yellowmegaman@gmail.com>'
description: 'Shoots old builds'
branding:
  icon: 'target'
  color: 'yellow'
inputs:
  commit_message:
    description: "what workflows we'd like to stop"
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    GITHUB_TOKEN: ${{ inputs.github_token }}
