name: test

on:
  push:
    branches:
      - master

jobs:
  build_canceller:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: shot
      uses: yellowmegaman/gh-build-canceller@v1.6
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        workflows_filter: "CI|pr|build_canceller"
